
spring:
  data:
    mongodb:
      uri: mongodb+srv://root:12345@cluster0.36rgb.mongodb.net/seafood?retryWrites=true&w=majority&appName=Cluster0
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB